name: 'Upload Episode from YouTube To Spotify'

on:
  push:
    paths:
      - episode.json
    branches: [main]

jobs:
  upload_episode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Episode from YouTube To Spotify
        uses: Schroedinger-Hat/youtube-to-spotify@v2.5.0
        env:
          SPOTIFY_EMAIL: ${{ secrets.SPOTIFY_EMAIL }}
          SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_PASSWORD }}
          EPISODE_PATH: /github/workspace
          EXTRACTOR_ARGS: "youtubetab:skip=webpage,youtube:player_skip=webpage,configs;visitor_data=${{secrets.VISITOR_DATA}}"
         
