name: 'Upload Spotify'

on:
  push:
    paths:
      - episode.json
    branches: [main]

jobs:
  upload_episode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: Check cookies file
        run: cat cookies.txt || echo "No cookies file found!"
        
      - name: Download video from YouTube with cookies
        run: yt-dlp --cookies cookies.txt -o "episode.mp4" "https://www.youtube.com/watch?v=tv_K9gG8QbQ"
        
      - name: Upload Episode from YouTube To Spotify
        uses: Schroedinger-Hat/youtube-to-spotify@v2.5.0
        env:
          SPOTIFY_EMAIL: ${{ secrets.SPOTIFY_EMAIL }}
          SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_PASSWORD }}
          EPISODE_PATH: /github/workspace
